### ISSUE TITLE
TypeError: MagicBellClient is not a constructor

### ISSUE THREAD

**Issue by genthalili** [magicbell-io/magicbell-core#6]
Hi, 

I'm getting an error in my js express project:
`(node:15712) UnhandledPromiseRejectionWarning: TypeError: MagicBellClient.createInstance is not a function`
same if I do `new MagicBellClient(..)`
`(node:15692) UnhandledPromiseRejectionWarning: TypeError: MagicBellClient is not a constructor`

and I'm importing it like this  : `import MagicBellClient from '@magicbell/core';`

None of any other package is causing similar issue? Or is this package not ment to be used in an express common js app (not typescript)?

**Comment by pavanjadhaw** [comment]
To import module using commonjs you'll have to do something like this, this should solve your issue.
More on this: https://nodejs.org/api/packages.html#packagejson-and-file-extensions


```
const MagicBellClient = require("@magicbell/core").default;
const { NotificationStore } = require("@magicbell/core");

(async () => {
  const userEmail = "customer@example.com";
  const apiKey = "MAGICBELL_API_KEY";

  const client = await MagicBellClient.createInstance({
    apiKey,
    userEmail,
  });

  const notificationsStore = new NotificationStore();
  await notificationsStore.fetch();
  console.log(
    `User ${userEmail} has ${notificationsStore.unreadCount} unread notifications.`
  );
})();
```

**Comment by pavanjadhaw** [comment]
Just tried with `"type": "module"` facing same issue as @genthalili with esmodule import as well
Seems to be related to https://github.com/jaredpalmer/tsdx/issues/165

```
pavan@orsted ~/Documents/source/magicbell.io/node-core-test $ cat package.json
{
  "name": "node-core-test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "type": "module",
  "dependencies": {
    "@magicbell/core": "^5.0.3"
  }
}
pavan@orsted ~/Documents/source/magicbell.io/node-core-test $ cat index.js
import MagicBellClient, { NotificationStore } from "@magicbell/core";

(async () => {
  const userEmail = "customer@example.com";
  const apiKey = "MAGICBELL_API_KEY";

  const client = await MagicBellClient.createInstance({
    apiKey,
    userEmail,
  });

  const notificationsStore = new NotificationStore();
  await notificationsStore.fetch();
  console.log(
    `User ${userEmail} has ${notificationsStore.unreadCount} unread notifications.`
  );
})();
pavan@orsted ~/Documents/source/magicbell.io/node-core-test $ node index.js
file:///Users/pavan/Documents/source/magicbell.io/node-core-test/index.js:7
  const client = await MagicBellClient.createInstance({
                                       ^

TypeError: MagicBellClient.createInstance is not a function
    at file:///Users/pavan/Documents/source/magicbell.io/node-core-test/index.js:7:40
    at file:///Users/pavan/Documents/source/magicbell.io/node-core-test/index.js:17:3
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
pavan@orsted ~/Documents/source/magicbell.io/node-core-test $
```
